app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired

class CreatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Çontent')
    category = SelectField('Category', coerce=int)
    submit = SubmitField('Publish')

app/posts/__init__.py
from flask import Blueprint

posts_bp = Blueprint('posts', __name__, template_folder='templates')

from app.posts import routes

app/posts/routes.py
from app.posts import posts_bp as posts

from flask import render_template, url_for, redirect, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.posts.forms import CreatePostForm
from app import db

from app.models import Post, Category


@posts.route('/posts_list')
def posts_list():
    posts = db.session.execute(
        db.select(Post).order_by(Post.id.desc())
    ).scalars().all()
    return render_template('posts_list.html', posts=posts)

@posts.route('/post_create', methods=['GET', 'POST'])
@login_required
def post_create():

    form = CreatePostForm()

    categories = Category.query.all()
    form.category.choices = [(0, 'No Category')] + [(c.id, c.name) for c in categories]

    if form.validate_on_submit():
        post = Post.create_post(
            title = form.title.data,
            content = form.content.data,
            user_id = current_user.id,
            category_id = form.category.data
        )
        db.session.add(post)
        db.session.commit()
        flash("Post creado exitosamente!", "alert-success")
        return redirect( url_for('posts.posts_list') )

    return render_template('/create_post.html', form=form)

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = db.session.get(Post, post_id)
    if not post:
        flash("Post no encontrado", "alert-danger")
        return redirect(url_for('posts.posts_list'))
    return render_template('post_single.html', post=post)

@posts.route('/post_edit')
def post_edit():
    pass

@posts.route('/post_delete/<int:post_id>')
def post_delete(post_id):
    post = db.session.get(Post, post_id)
    if not post:
        flash("Post no encontrado", "alert-danger")
        return redirect(url_for('posts.posts_list'))
    db.session.delete(post)
    db.session.commit()
    flash("Post eliminado exitosamente!", "alert-success")
    return redirect(url_for('posts.posts_list'))

app/posts/templates/create_post.html
{% extends "base.html" %}

{% block content %}
<div id="create-post">
    <section class="new-post-form">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Create Post</h2>
                    <div>
                        <form method="post">
                            {{ form.hidden_tag() }}
                            <div>
                                {{ form.title.label }}
                                {{ form.title(size=100) }}
                                {% for error in form.title.errors %} 
                                    <span style="color: red; display: block;">[{{ error }}]</span> 
                                {% endfor %}
                            </div>
                            <div>
                                {{ form.category.label }}
                                {{ form.category(class="form-control") }}
                                {% for error in form.category.errors %} 
                                    <span style="color: red;">[{{ error }}]</span> 
                                {% endfor %}
                            </div>

                            <div>
                                {{ form.content.label }}
                                {{ form.content }}
                                {% for error in form.content.errors %} 
                                    <span style="color: red; display: block;">[{{ error }}]</span> 
                                {% endfor %}
                            </div>
                            <div>
                                {{ form.submit }}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

app/posts/templates/post_single.html
{% extends "base.html" %}

{% block content %}
<div id="post-{post.id}">
    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h1 class="title">
                            {{ post.title }}
                        </h1>
                        {% if post.category %}
                            <h3>Categoría: {{ post.category.name }}</h3>
                        {% endif %}
                        <h4 class="subtitle">
                            {{ post.create_date.strftime('%d/%m/%Y %H:%M') }}
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="actions">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <ul>
                        <li><a href="#">Editar Post</a></li>
                        <li><a href="{{ url_for('posts.post_delete', post_id=post.id) }}">Eliminar Post</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {{ post.content }}
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

app/posts/templates/posts_list.html
{% extends "base.html" %}

{% block content %}
<div id="blog">
    <section class="hero">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>Mi Foro</h1>
                </div>
            </div>
        </div>
    </section>
    {% if current_user.is_authenticated %}
        <section class="post-menu">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="nav-post">
                            <nav>
                                <ul>
                                    <li>
                                        <a href="{{ url_for('posts.post_create') }}">Crear nuevo post</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
    <section class="posts-list">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <div>
                        <ul>
                            {% if posts %}
                                {% for post in posts %}
                                    <li><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></li>
                                {% endfor %}
                            {% else %}
                                <li>No hay posts disponibles.</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock content %}